import Head from 'next/head';
import Layout from '../../components/Layout';
import Swal from 'sweetalert2';
import Link from 'next/link';

const Shortener = ({ url }) => {
  const copyText = () => {
    Swal.fire('Copied!', '', 'success');
    navigator.clipboard.writeText(url.shortUrl);
  };

  return (
    <div className="contact">
      <Head>
        <title>Shortened URL</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="shortener">
        <Layout>
          <main>
            <div className="content">
              <h1>Your shortened URL</h1>
              <p>Copy the shortened link and share it in messages, texts, posts, websites and other locations.</p>
            </div>

            <div className="urlBox">
              <br />
              <br />
              <div className="formUrl">
                <input type="text" name="" value={url && url.shortUrl} readOnly id="" className="shortenurl" />
                <div className="formButton">
                  <input type="button" value="Copy URL" className="copy" onClick={copyText} />
                </div>
              </div>
              <div className="formUrl"></div>

              <p className="boxText">
                Long URL: &nbsp;
                <Link href="/">{url ? url.origUrl : ''}</Link>
                <br />
                <br />
                Create another <Link href="/">shortened URL</Link>
              </p>
            </div>

            {/* <div className="content">
              <h2>Share URL</h2>
              <div className="socialBox">
                <p>
                  <Link href="/" className="snb snbfacebook">
                    Facebook
                  </Link>
                  <Link href="/" className="snb snbtwitter">
                    Twitter
                  </Link>
                  <Link href="/" className="snb snbpinterest">
                    Pinterest
                  </Link>
                  <Link href="/" className="snb snbtumblr">
                    Tumblr
                  </Link>
                </p>
              </div>
            </div> */}
          </main>
        </Layout>
      </div>
    </div>
  );
};

export default Shortener;

export async function getServerSideProps(context) {
  const response = await fetch(`https://urlshortener.hassuu.com/check/${context.query.id}`);
  const data = await response.json();
  const { url } = data;

  return {
    props: { url }, // will be passed to the page component as props
  };
}
