import Head from 'next/head';
import Layout from '../components/Layout';
import { useState, useEffect } from 'react';

import { sendMail } from '../utils/apiRequests';

const Contact = () => {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [message, setMessage] = useState('');

  const mailSender = async (e) => {
    e.preventDefault();

    const response = await sendMail(name, email, message);
    console.log('email response : ', response);
  };

  return (
    <div className="contact">
      <Head>
        <title>URL Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <main>
          <div className="content">
            <h1>Contact our Team</h1>
            <div className="formBox">
              <form onSubmit={mailSender}>
                <p className="formText">
                  Name <br />
                  <input type="text" name="name" required onChange={(e) => setName(e.target.value)} />
                </p>
                <p className="formText">
                  E-mail <br />
                  <input type="email" name="email" required onChange={(e) => setEmail(e.target.value)} />
                </p>
                <p className="formText">
                  Message <br />
                  <textarea name="message" required onChange={(e) => setMessage(e.target.value)}></textarea>
                </p>
                {/* <div class="h-captcha" data-sitekey="7583a637-1b65-4cd3-8687-94c48c1fdc04"></div> */}

                <p className="button">
                  <input type="submit" value="Send" name="submit" />
                  <input type="reset" value="Clean" name="submit" />
                </p>
              </form>
            </div>
          </div>
        </main>
      </Layout>
    </div>
  );
};

export default Contact;
