import axios from 'axios';
import Head from 'next/head';
import Footer from '../components/Footer';
import { useRouter } from 'next/router';
import Link from 'next/link';

const Swal = require('sweetalert2');

const Home = () => {
  const router = useRouter();

  const submitHandler = async (e) => {
    e.preventDefault();

    const url = e.target.url.value;
    let checkStatus, id;

    try {
      const response = await axios({
        baseURL: '/',
        url: 'api/short',
        method: 'post',
        headers: {
          Accept: 'application/json',
          'Content-Type': 'application/json',
        },
        data: JSON.stringify({ origUrl: url }),
      });
      const { status, data } = response;
      checkStatus = status;
      id = data.urlId;
      console.log(data);
    } catch (e) {
      Swal.fire('Invalid URL', 'Please enter correct one', 'question');
      console.log('error');
      console.log(e);
    }

    if (checkStatus === 200) {
      router.push(`/shortener/${id}`);
    }
  };

  const comingSoon = (e) => {
    e.preventDefault();

    Swal.fire('Coming Soon :)', '', 'question');
  };

  return (
    <div className="app">
      <Head>
        <title>URL Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="logo">
          <Link href="/">URL SHORTENER</Link>
        </div>
        <div className="urlBox">
          <h1>Paste the URL to be shortened</h1>

          <form onSubmit={submitHandler}>
            <div className="formUrl">
              <input type="text" placeholder="Enter the link here" name="url" />
              <div className="formButton">
                <input type="submit" value="Shorten URL" />
              </div>
            </div>
          </form>

          <p className="boxText">
            URL SHORTENER is a free tool to shorten a URL or reduce a link
            <br />
            Use our URL Shortener to create a shortened link making it easy to remember
          </p>
        </div>

        <div className="premiumBox">
          <h2>Want More? Try Premium Features!</h2>
          <p className="boxText">
            Custom short links, powerful dashboard, detailed analytics, API, UTM builder, QR codes, browser extension, 50+ app integrations and support. Only
            $9/month.
          </p>

          <Link href="/">
            <a className="colorButton" onClick={comingSoon}>
              Go Premium
            </a>
          </Link>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Home;
