import Head from 'next/head';
import Layout from '../components/Layout';

const TOS = () => {
  return (
    <div className="tos">
      <Head>
        <title>Terms of Service</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <main>
          <div className="content">
            <h1>Terms of Service</h1>
            <p>
              This page explains the terms of use of Short URL, the user when using the shortener site is conditioned to the acceptance of the terms and
              conditions of use.
            </p>

            <h2>Conditions of use</h2>
            <p>The site is available for access to all users and therefore you need to agree with the conditions of use when using our services.</p>
            <p>In order to provide a secure service for users it is not allowed to create short links that redirect to URLs that have:</p>

            <ul>
              <li className="list">Content that spreads phishing, malware or viruses</li>
              <li className="list">Abusive or suspicious content</li>
              <li className="list">Pornographic, sexual, violent or prejudiced content</li>
              <li className="list">Content related to drugs, weapons or drinks</li>
              <li className="list">{`Any content that may infringe other people's rights`}</li>
              <li className="list">Disgusting, explicit or offensive content that causes any kind of discomfort to other users</li>
              <li className="list">Child or child-related content</li>
              <li className="list">Pop-ups, scripts and malicious code</li>
              <li className="list">Pages that provide information that is false, inaccurate or incomplete</li>
              <li className="list">Double redirection</li>
              <li className="list">Pages without content</li>
              <li className="list">Pages created recently</li>
              <li className="list">Pages without authority</li>
              <li className="list">Content to collect data and personal information from users</li>
            </ul>

            <p>Do not use our URL shortener service for:</p>

            <ul>
              <li className="list">Commercial purposes</li>
              <li className="list">Ad campaigns</li>
              <li className="list">Emails campaigns</li>
              <li className="list">Spam material</li>
            </ul>

            <p>
              All URLs are checked and analyzed by our team, any shortened URL that leads to the landing page that meets the above conditions can be deleted. If
              we notice any abusive behavior against our terms of service, the shortened URL will be deleted without notice. Shortened URLs that do not receive
              at least 1 click per month are also removed.
            </p>

            <h2>Disclaimer</h2>
            <p>
              We offer a free service for all users, so Short URL does not warrant that the site or services are uninterrupted, secure or error-free. Due to a
              large number of emails received, we may not respond to all emails.
            </p>

            <h2>Terms updates</h2>
            <p>
              Short URL reserves the right to update or change these terms of use at any time. The most current version of the terms will be posted on this
              page.
            </p>
            <p></p>
          </div>
        </main>
      </Layout>
    </div>
  );
};

export default TOS;
